[pytest]
markers =   xyz: Window handling tests
            pop: practice test 




log_cli = true
log_cli_level = INFO
addopts = --screenshot=only-on-failure
log_file = reports/test.log
log_file_level = INFO

log_format = %(asctime)s | %(levelname)s | %(message)s
log_date_format = %Y-%m-%d %H:%M:%S



